SELECT MRA_ID AS MRA, MRA_TITLE AS Title, MRA_LINK AS MRALink, ADD_ID AS Addendum, ADD_YEAR AS YearSubmitted, ADD_LINK AS AddendumLink
FROM MRA AS M, Addendum AS A
WHERE M.MRA_ID = A.MRA_ID
ORDER BY M.MRA_ID